import { db } from '../src/lib/db'

const sampleProperties = [
  {
    jenisProperti: 'Rumah',
    statusListing: 'Dijual',
    hargaJualSewa: 'Rp 850.000.000',
    alamatLengkap: 'Jl. Sudirman No. 123, Kelurahan Kemanggisan, Kecamatan Palmerah, Jakarta Barat',
    luasTanah: 120,
    luasBangunan: 90,
    jumlahLantai: 2,
    kamarTidur: 3,
    kamarMandi: 2,
    carportGarasi: '1 mobil',
    arahHadap: 'Utara',
    kondisi: 'Seken',
    furnishing: 'Semi Furnished',
    jenisSertifikat: 'SHM',
    imb: 'Ada',
    pbb: '3567890123456789',
    kapasitasListrik: 2200,
    tipeMeteran: 'Token',
    sumberAirUtama: 'PDAM',
    tandonAir: 'Ada',
    kapasitasTandon: 500,
    aksesJalan: 'Aspal',
    lebarJalan: 6,
    bebasBanjir: 'Ya',
    keamananKompleks: '24 Jam',
    iplBulanan: 'Rp 150.000',
    fasilitasTerdekat: 'Mall, Sekolah, Rumah Sakit, Bank, Restoran',
    namaPemilik: 'Budi Santoso',
    noKontakAktif: '0812-3456-7890',
    kondisiProperti: 'Dihuni Pemilik',
    komisiAgen: '2.5%',
    photos: JSON.stringify([])
  },
  {
    jenisProperti: 'Apartemen',
    statusListing: 'Disewa',
    hargaJualSewa: 'Rp 45.000.000/tahun',
    alamatLengkap: 'Jl. Gatot Subroto No. 45, Karet Semanggi, Setiabudi, Jakarta Selatan',
    luasTanah: null,
    luasBangunan: 65,
    jumlahLantai: 1,
    kamarTidur: 2,
    kamarMandi: 1,
    carportGarasi: 'Tidak ada',
    arahHadap: 'Timur',
    kondisi: 'Baru',
    furnishing: 'Full Furnished',
    jenisSertifikat: 'SHMRS',
    imb: 'Ada',
    pbb: '4567890123456789',
    kapasitasListrik: 1300,
    tipeMeteran: 'Pascabayar',
    sumberAirUtama: 'PDAM',
    tandonAir: 'Ada',
    kapasitasTandon: null,
    aksesJalan: 'Aspal',
    lebarJalan: 8,
    bebasBanjir: 'Ya',
    keamananKompleks: '24 Jam',
    iplBulanan: 'Rp 800.000',
    fasilitasTerdekat: 'Mall, Sekolah, Rumah Sakit, Bank, MRT Station',
    namaPemilik: 'Siti Nurhaliza',
    noKontakAktif: '0813-2345-6789',
    kondisiProperti: 'Kosong',
    komisiAgen: '1 bulan sewa',
    photos: JSON.stringify([])
  },
  {
    jenisProperti: 'Ruko',
    statusListing: 'Dijual',
    hargaJualSewa: 'Rp 2.500.000.000',
    alamatLengkap: 'Jl. MH Thamrin No. 88, Gondangdia, Menteng, Jakarta Pusat',
    luasTanah: 80,
    luasBangunan: 240,
    jumlahLantai: 3,
    kamarTidur: null,
    kamarMandi: 2,
    carportGarasi: 'Tidak ada',
    arahHadap: 'Selatan',
    kondisi: 'Seken',
    furnishing: 'Unfurnished',
    jenisSertifikat: 'HGB',
    imb: 'Ada',
    pbb: '5678901234567890',
    kapasitasListrik: 3500,
    tipeMeteran: 'Pascabayar',
    sumberAirUtama: 'PDAM',
    tandonAir: 'Ada',
    kapasitasTandon: 1000,
    aksesJalan: 'Aspal',
    lebarJalan: 10,
    bebasBanjir: 'Ya',
    keamananKompleks: 'One Gate System',
    iplBulanan: 'Rp 300.000',
    fasilitasTerdekat: 'Bank, Restoran, Hotel, Kantor, Mall',
    namaPemilik: 'Ahmad Wijaya',
    noKontakAktif: '0814-3456-7890',
    kondisiProperti: 'Sedang Disewa',
    komisiAgen: '3%',
    photos: JSON.stringify([])
  },
  {
    jenisProperti: 'Tanah',
    statusListing: 'Dijual',
    hargaJualSewa: 'Rp 1.200.000.000',
    alamatLengkap: 'Jl. Raya Bogor No. 200, Cibubur, Jakarta Timur',
    luasTanah: 300,
    luasBangunan: null,
    jumlahLantai: null,
    kamarTidur: null,
    kamarMandi: null,
    carportGarasi: null,
    arahHadap: 'Barat',
    kondisi: null,
    furnishing: null,
    jenisSertifikat: 'SHM',
    imb: 'Tidak Ada',
    pbb: '6789012345678901',
    kapasitasListrik: null,
    tipeMeteran: null,
    sumberAirUtama: null,
    tandonAir: null,
    kapasitasTandon: null,
    aksesJalan: 'Aspal',
    lebarJalan: 8,
    bebasBanjir: 'Tidak',
    keamananKompleks: 'Tidak Ada',
    iplBulanan: null,
    fasilitasTerdekat: 'Sekolah, Pasar, Masjid, Klinik',
    namaPemilik: 'Diana Putri',
    noKontakAktif: '0815-4567-8901',
    kondisiProperti: 'Kosong',
    komisiAgen: '2%',
    photos: JSON.stringify([])
  },
  {
    jenisProperti: 'Gudang',
    statusListing: 'Disewa',
    hargaJualSewa: 'Rp 150.000.000/tahun',
    alamatLengkap: 'Jl. Daan Mogot No. 150, Kedoya, Kebon Jeruk, Jakarta Barat',
    luasTanah: 500,
    luasBangunan: 400,
    jumlahLantai: 1,
    kamarTidur: 1,
    kamarMandi: 2,
    carportGarasi: '2 mobil + 1 truck',
    arahHadap: 'Utara',
    kondisi: 'Butuh Renovasi',
    furnishing: 'Unfurnished',
    jenisSertifikat: 'HGB',
    imb: 'Ada',
    pbb: '7890123456789012',
    kapasitasListrik: 5500,
    tipeMeteran: 'Pascabayar',
    sumberAirUtama: 'Sumur Bor',
    tandonAir: 'Ada',
    kapasitasTandon: 2000,
    aksesJalan: 'Aspal',
    lebarJalan: 12,
    bebasBanjir: 'Ya',
    keamananKompleks: '24 Jam',
    iplBulanan: 'Rp 500.000',
    fasilitasTerdekat: 'Toll Access, Pasar, Bank, Restoran',
    namaPemilik: 'Rudi Hermawan',
    noKontakAktif: '0816-5678-9012',
    kondisiProperti: 'Kosong',
    komisiAgen: '1 bulan sewa',
    photos: JSON.stringify([])
  }
]

async function seedData() {
  try {
    console.log('🌱 Menambahkan data sampel properti...')
    
    for (const property of sampleProperties) {
      await db.property.create({
        data: property
      })
      console.log(`✅ Data properti ditambahkan: ${property.jenisProperti} - ${property.alamatLengkap}`)
    }
    
    console.log('🎉 Semua data sampel berhasil ditambahkan!')
  } catch (error) {
    console.error('❌ Error saat menambahkan data:', error)
  } finally {
    await db.$disconnect()
  }
}

seedData()